
- name: Configure Web Server
  hosts: web
  become: yes
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Deploy web application
      copy:
        src: ../app/index.html
        dest: /var/www/html/index.html
